# Generated by Django 5.0.7 on 2025-11-11 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                ("host", models.CharField(max_length=255, verbose_name="Хост")),
                ("port", models.PositiveIntegerField(default=22, verbose_name="Порт")),
                (
                    "username",
                    models.CharField(max_length=120, verbose_name="Имя пользователя"),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("password", "Password"),
                            ("private_key", "Private Key"),
                        ],
                        default="password",
                        max_length=20,
                        verbose_name="Тип аутентификации",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Пароль"
                    ),
                ),
                (
                    "private_key",
                    models.TextField(
                        blank=True, default="", verbose_name="Приватный ключ"
                    ),
                ),
                (
                    "passphrase",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Пароль для ключа",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="servers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сервер",
                "verbose_name_plural": "Серверы",
                "ordering": ["-created_at"],
            },
        ),
    ]
