# Generated by Django 5.0.7 on 2025-11-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Баланс"
            ),
        ),
    ]
