# Generated by Django 5.0.7 on 2025-11-11 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_userprofile_balance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="subscription_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Подписка истекает"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_type",
            field=models.CharField(
                choices=[("none", "Без подписки"), ("pro", "PRO"), ("plus", "PLUS")],
                default="none",
                max_length=20,
                verbose_name="Тип подписки",
            ),
        ),
        migrations.CreateModel(
            name="AllocatedServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                ("host", models.CharField(max_length=255, verbose_name="Хост")),
                ("port", models.PositiveIntegerField(default=22, verbose_name="Порт")),
                (
                    "username",
                    models.CharField(max_length=120, verbose_name="Имя пользователя"),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Пароль"
                    ),
                ),
                (
                    "cpu_cores",
                    models.PositiveIntegerField(default=1, verbose_name="Ядра CPU"),
                ),
                (
                    "memory_gb",
                    models.PositiveIntegerField(default=1, verbose_name="Память (GB)"),
                ),
                (
                    "disk_gb",
                    models.PositiveIntegerField(default=10, verbose_name="Диск (GB)"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Истекает"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocated_servers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выданный сервер",
                "verbose_name_plural": "Выданные серверы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Пополнение"),
                            ("subscription_pro", "Покупка PRO"),
                            ("subscription_plus", "Покупка PLUS"),
                            ("admin_grant", "Выдача админом"),
                        ],
                        max_length=20,
                        verbose_name="Тип транзакции",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
                "ordering": ["-created_at"],
            },
        ),
    ]
