# Generated by Django 5.0.7 on 2025-11-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_userprofile_subscription_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
    ]
