# Generated by Django 5.0.7 on 2025-11-13 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_server_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpu_percent",
                    models.FloatField(blank=True, null=True, verbose_name="CPU %"),
                ),
                (
                    "memory_percent",
                    models.FloatField(blank=True, null=True, verbose_name="Память %"),
                ),
                (
                    "memory_used_mb",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Память использовано (MB)"
                    ),
                ),
                (
                    "memory_total_mb",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Память всего (MB)"
                    ),
                ),
                (
                    "disk_percent",
                    models.FloatField(blank=True, null=True, verbose_name="Диск %"),
                ),
                (
                    "disk_used_gb",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Диск использовано (GB)"
                    ),
                ),
                (
                    "disk_total_gb",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Диск всего (GB)"
                    ),
                ),
                (
                    "network_in_mb",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Сеть входящий (MB)"
                    ),
                ),
                (
                    "network_out_mb",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Сеть исходящий (MB)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создана"
                    ),
                ),
                (
                    "allocated_server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="api.allocatedserver",
                        verbose_name="Выданный сервер",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="api.server",
                        verbose_name="SSH Сервер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Метрика сервера",
                "verbose_name_plural": "Метрики серверов",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="api_serverm_created_1bb2fe_idx"
                    ),
                    models.Index(
                        fields=["server", "-created_at"],
                        name="api_serverm_server__415f0b_idx",
                    ),
                    models.Index(
                        fields=["allocated_server", "-created_at"],
                        name="api_serverm_allocat_15bb03_idx",
                    ),
                ],
            },
        ),
    ]
